dgtlmoon/changedetection.io

backend/__init__.py, backend/store.py, backend/templates/scrub.html, backend/templates/settings.html
Scrub - Optionally delete history snapshots newer than timestamp
=> Re #30 - Delete history watch snapshots

docker-compose.yml
Created a docker-compose.yml file for easier updating using docker-compose
=> Created docker-compose file

backend/__init__.py, backend/run_all_tests.sh, backend/tests/test_notification.py, backend/tests/util.py, docker-compose.yml
Re #65 - Append BASE_URL env var to the notification if it is set
=> Re #65 - Append BASE_URL env var to the notification if it is set

backend/__init__.py, backend/fetch_site_status.py, backend/store.py, backend/templates/edit.html, backend/tests/test_css_selector.py, requirements.txt
=> CSS selector filter

Dockerfile
Rewrites the Dockerfile to take advantage of multistage builds for dependencies. Reduces the final image size to ~169MB.
=> Modifies Dockerfile to use multistage builds

backend/static/css/styles.css, backend/templates/base.html, backend/templates/edit.html, backend/templates/settings.html, backend/templates/watch-overview.html
Lots of fixes
- #48 
- responsive table layout for the watch list
- few more improvements
=> Mobile fixes

backend/__init__.py, backend/forms.py, backend/run_all_tests.sh, backend/static/styles/package.json, backend/static/styles/styles.css, backend/static/styles/styles.scss, backend/templates/_helpers.jinja, backend/templates/edit.html, backend/templates/settings.html, backend/tests/test_ignore_text.py, requirements.txt
Remove custom validation logic and use wtforms for handling
=> Use wtforms handler

backend/__init__.py, backend/html_tools.py, backend/store.py, backend/templates/edit.html, backend/templates/settings.html, backend/tests/test_watch_fields_storage.py
=> #110 global recheck time

backend/__init__.py, backend/forms.py, backend/static/styles/styles.css, backend/static/styles/styles.scss, backend/templates/_helpers.jinja, backend/templates/watch-overview.html
=> Re #135 - refactor the quick add widget

README.md, backend/fetch_site_status.py, backend/html_tools.py, backend/tests/test_jsonpath_selector.py
=> Re #154 Ldjson extract parse

changedetectionio/__init__.py
=> Re #232 - Use a copy of the datastore incase it changes 

changedetectionio/__init__.py
Makes the GUID follow a unique ID for each event
=> Re #239 - Individual GUID for watch+changeevent

changedetectionio/__init__.py, changedetectionio/store.py, changedetectionio/tests/test_clone.py
=> Re #308 - Adding test and including settings in clone operation

changedetectionio/__init__.py, changedetectionio/store.py, changedetectionio/templates/watch-overview.html, changedetectionio/tests/test_backend.py
So you can have a password for the site, but still get to your feeds
=> RSS allow access via token

changedetectionio/content_fetcher.py, changedetectionio/store.py, changedetectionio/tests/test_notification.py, changedetectionio/update_worker.py
Closes #342 notification encoding
=> Re #342 notification encoding

changedetectionio/__init__.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/store.py, changedetectionio/templates/settings.html, changedetectionio/tests/conftest.py, changedetectionio/tests/test_ignore_text.py, changedetectionio/tests/test_ignorewhitespace.py, changedetectionio/update_worker.py
=> Re #133 Option for ignoring whitespacing

changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/html_tools.py, changedetectionio/tests/test_errorhandling.py, changedetectionio/tests/util.py, changedetectionio/update_worker.py, requirements.txt
Also shows the error in the listing page
needs some test
=> Better handling of EmptyReply exception, always bump 'last_checked' in the case of an error

changedetectionio/__init__.py
send_from_directory needs to be abs path
closes #348
=> Heroku tweaks (backup download)

changedetectionio/forms.py, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_notification.py
=> Notification settings defaults and validation

changedetectionio/__init__.py, changedetectionio/forms.py, changedetectionio/tests/test_auth.py, changedetectionio/tests/util.py
=> Simple HTTP auth

changedetectionio/tests/test_notification.py, changedetectionio/update_worker.py
=> Fix bug where diff and diff_full were switched in notification templates.

changedetection.py
to allow listening not on 0.0.0.0.
=> Introduce -h option

changedetectionio/__init__.py, changedetectionio/static/styles/styles.css, changedetectionio/static/styles/styles.scss, changedetectionio/templates/base.html
Trying to find a way to pay for my time in maintaining this wonderful application that so many people and organisations rely on.
=> Include link to changedetection.io hosted option

changedetectionio/html_tools.py, changedetectionio/tests/test_jsonpath_selector.py
Related to https://github.com/dgtlmoon/changedetection.io/issues/462
Needs some small unit test update still
=> JSON use the original char encoding

changedetectionio/fetch_site_status.py, changedetectionio/tests/test_security.py, changedetectionio/update_worker.py
Suggested by https://github.com/JamieSlome
=> Security update - Protect against file:/// type access by webdriver/chrome.

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_errorhandling.py, changedetectionio/tests/test_ignorestatuscode.py, changedetectionio/tests/util.py
* Ability to ignore status codes as a per-site setting
=> Allow changedetector to ignore status codes as a per-site setting (#479)

changedetectionio/__init__.py, changedetectionio/tests/test_backend.py
=> RSS feed should contain CDATA of rendered differences

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/static/js/tabs.js, changedetectionio/static/styles/diff.css, changedetectionio/static/styles/diff.scss, changedetectionio/static/styles/styles.css, changedetectionio/static/styles/styles.scss, changedetectionio/store.py, changedetectionio/templates/diff.html, changedetectionio/templates/edit.html, changedetectionio/templates/preview.html, changedetectionio/templates/settings.html, changedetectionio/update_worker.py
=> Screenshot last check

changedetectionio/__init__.py, changedetectionio/forms.py, changedetectionio/static/js/notifications.js, changedetectionio/templates/_common_fields.jinja, changedetectionio/templates/base.html, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html, changedetectionio/tests/test_notification.py, changedetectionio/tests/util.py
Needed for removing the 'trigger_check' field in https://github.com/dgtlmoon/changedetection.io/pull/512 but also just generally way more awesome
=> AJAX button for sending test notifications

changedetectionio/__init__.py
=> Re #521 - Don't process this watch into the RSS if theres not enough data to examine

changedetectionio/notification.py, changedetectionio/templates/_common_fields.jinja
=> Discord:// notifications should be cut to 2000 chars or Discord will not process them.

changedetectionio/__init__.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/html_tools.py, changedetectionio/store.py, changedetectionio/templates/settings.html, changedetectionio/tests/test_api.py, changedetectionio/tests/test_html_to_text.py, changedetectionio/tests/test_ignorehyperlinks.py
=> Render hyperlinks option

changedetectionio/__init__.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/tests/test_notification.py
=> Re #569 corrupted diffs

docker-compose.yml
cf. https://github.com/dgtlmoon/changedetection.io/discussions/587
=> Fix PLAYWRIGHT_DRIVER_URL example

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/static/styles/styles.css, changedetectionio/static/styles/styles.scss, changedetectionio/store.py, changedetectionio/templates/_common_fields.jinja, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html
Overrides the system proxy, allowing you to choose between different proxies for the requests
add a file called `proxies.txt` to your data-directory that looks like
```
http://10.8.0.1:3128, nice one USA default
http://10.8.0.2:3128, my other one
```
or just simply
```
http://10.8.0.1:3128
http://10.8.0.2:3128
```
You will then get a list
=> Ability to specify a list of proxies to choose from, always using the first one by default

changedetectionio/__init__.py, changedetectionio/fetch_site_status.py, changedetectionio/importer.py, changedetectionio/templates/edit.html, changedetectionio/templates/import.html, changedetectionio/tests/test_import.py, changedetectionio/tests/test_xpath_selector.py
Closes #557
https://distill.io/docs/web-monitor/how-export-and-import-monitors/
=> Distill.io import

changedetectionio/content_fetcher.py
=> Fix PLAYWRIGHT_DRIVER_URL default value

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/static/js/global-settings.js, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html
=> Re #214 - configurable extra wait seconds for webdriver requests

changedetectionio/html_tools.py, changedetectionio/tests/test_xpath_selector.py
=> Fix encoding errors with XPath filters from UTF-8 responses

changedetectionio/tests/test_trigger.py
=> Re #616 - adding extra test

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/tests/test_backend.py
=> Re #651 - Adding test and fixing accidently broken implementation

changedetectionio/__init__.py
=> Fixing RSS feed HTML content formatting

changedetectionio/__init__.py, changedetectionio/static/js/diff-overview.js, changedetectionio/templates/diff.html
=> Screenshot on the diff tab refactor

changedetectionio/__init__.py, changedetectionio/forms.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/run_all_tests.sh, changedetectionio/store.py, changedetectionio/templates/settings.html
Adds a configuration in the main settings that applies a Jitter Delay +/- to watches
=> Re #580 - Jitter delay

changedetectionio/fetch_site_status.py
=> Some changes werent getting triggered because the previous checksum only recorded when an event occurred

docker-compose.yml
=> Improve docker-compose.yml browserless/playwright docker container, add env var for STEALTH and BLOCK_ADS

changedetectionio/__init__.py, changedetectionio/fetch_site_status.py, changedetectionio/store.py, changedetectionio/templates/watch-overview.html, changedetectionio/tests/test_api.py, changedetectionio/update_worker.py
=> Only set last_changed on the second snapshot, update existing watches

changedetectionio/__init__.py, changedetectionio/changedetection.py, changedetectionio/store.py, changedetectionio/templates/clear_all_history.html, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html
\+ other consistency, elaboration in language surrounding the action
Replaces #720 
Closes #717
=> lang: prefer 'clear (snap) history' to 'scrub'

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/static/js/watch-settings.js, changedetectionio/templates/edit.html
=> Re #664 - Use HTTP Request Headers override (Cookie, etc) in playwright

changedetectionio/__init__.py, changedetectionio/apprise_asset.py, changedetectionio/notification.py
=> Use our own apprise asset format

changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/templates/edit.html
=> Ability to specify JS before running change-detection

changedetectionio/fetch_site_status.py
Merge result with regex_matched_output instead of adding the first result
=> Return all regex results instead of first match

changedetectionio/forms.py, changedetectionio/html_tools.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/notification.py, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html, changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/update_worker.py
=> Send notification after CSS/xPath filter is missing after more than 6 (configurable) attempts

changedetectionio/fetch_site_status.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_extract_regex.py, changedetectionio/update_worker.py
Also closes https://github.com/dgtlmoon/changedetection.io/issues/674
=> Refactor of extract regex

changedetectionio/html_tools.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_xpath_selector.py
=> Enhancement - support xPath text() function filter, for example "//title/text()" in RSS feeds

changedetectionio/tests/test_filter_exist_changes.py, changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/update_worker.py
Adding test case, stop filter failure detection from interfering with results
=> Filter failure detection notification interfering with results

changedetectionio/__init__.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/templates/_pagination.jinja, changedetectionio/templates/watch-overview.html
=> Column sorting

changedetectionio/fetch_site_status.py, changedetectionio/run_all_tests.sh, changedetectionio/tests/fetchers/test_content.py, changedetectionio/tests/util.py, changedetectionio/tests/visualselector/__init__.py, changedetectionio/tests/visualselector/conftest.py, changedetectionio/tests/visualselector/test_fetch_data.py, changedetectionio/update_worker.py
=> Be sure visual-selector data is set when filter is not found

changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/static/js/watch-settings.js, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_notification.py, changedetectionio/update_worker.py
Closes #809
Closes #562
Closes #865
=> Cleaner separation of watch/global notification settings

changedetectionio/static/images/play.svg, changedetectionio/templates/watch-overview.html
=> Use play and pause icon

changedetectionio/__init__.py, changedetectionio/fetch_site_status.py, changedetectionio/store.py
Better format for configuring locations/proxies
```
{
"usa-1": {
"label": "USA",
"url": "http://10.8.0.3:3128"
},
"usa-2": {
"label": "USA #2  (5 minute recheck)",
"url": "http://some-proxy-provider.io",
"reuse_time_minimum": 300
}
}
```
=> Use proxies.json instead of proxies.txt

requirements.txt
https://github.com/caronc/apprise/releases/tag/v1.1.0
📣 New Notification Services:
[Bulksms](https://github.com/caronc/apprise/wiki/Notify_bulksms) Support added. (https://github.com/caronc/apprise/pull/683)
[SMSEagle](https://github.com/caronc/apprise/wiki/Notify_smseagle) Notification Support Added (https://github.com/caronc/apprise/pull/661)
🐛 Bugfixes
`signal://` to support groups ending with an = (equal) symbol (https://github.com/caronc/apprise/pull/670)
`opsgenie://` no longer double stacks body in larger messages (https://github.com/caronc/apprise/pull/655)
`bark://` correctly handles custom ports (https://github.com/caronc/apprise/pull/672)
`mailto://` delivery improvements to better follow mail guidelines (less likely to get email identified as spam) …
=> Bump notification library 

changedetectionio/__init__.py, changedetectionio/model/Watch.py
Related https://github.com/dgtlmoon/changedetection.io/discussions/1030#discussioncomment-3897070
Closes #1032 1032
=> Windows diff file handling improvements

CONTRIBUTING.md
Hi,
Just fixing the command in the CONTRIBUTING.md
=> update path for validation in the CONTRIBUTING.md

Dockerfile, README.md, changedetectionio/run_all_tests.sh, requirements.txt
Related to https://github.com/dgtlmoon/changedetection.io/pull/1009
Now we should see in the test log that jq was tested for
=> Jq conditional pip requirements.txt include in linux

.github/test/Dockerfile-alpine, .github/workflows/test-container-build.yml, Dockerfile, changedetectionio/run_all_tests.sh, requirements.txt
=> Playwright conditional fix musl alpine

changedetectionio/model/Watch.py, changedetectionio/update_worker.py
=> Adding `check_count` and sorting vars

requirements.txt
https://github.com/caronc/apprise/releases/tag/v1.2.0
Adds Mastodon support
=> Bump notification library

changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/tests/test_notification.py
=> Re #1148 - Notification screenshot/JPEG was not being regenerated correctly

changedetectionio/__init__.py, changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/static/js/diff-overview.js, changedetectionio/static/styles/diff.css, changedetectionio/static/styles/scss/diff.scss, changedetectionio/templates/diff.html, changedetectionio/templates/edit.html, changedetectionio/tests/test_extract_csv.py
=> Simple extract data by regex from all historical watch text

changedetectionio/blueprint/price_data_follower/__init__.py, changedetectionio/fetch_site_status.py
=> Re #1207 - Dont scan for ldjson data when 'no' was clicked on the suggestion

changedetectionio/res/xpath_element_scraper.js
=> Fetcher + VisualSelector - xpath filter with attribute filter was breaking the element finder

changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/update_worker.py
=> Filter failure notification tokens 

docker-compose.yml
This fixes https://github.com/dgtlmoon/changedetection.io/issues/1079 .
I just changed version number from 2 to 3 and it works perfectly with portainer
=> Update the docker compose file to v3 (#1079)

docker-compose.yml
=> Remove docker-compose version 

requirements.txt
=> pip: eventlet doesnt support dnspython >=2.3.0

.github/workflows/containers.yml, .github/workflows/test-container-build.yml
Closes https://github.com/dgtlmoon/changedetection.io/pull/1332
Closes https://github.com/dgtlmoon/changedetection.io/issues/1335
But also adds container building test
=> Buildx error

changedetectionio/content_fetcher.py
Where playwright needed screenshot called twice to make the full screen screenshot be actually fullscreen
=> Removing old bug fix 

changedetectionio/__init__.py, changedetectionio/api/api_v1.py, changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/tests/test_security.py
=> Possible stored XSS in watch list - Only permit HTTP/HTTP/FTP by default - override with env var `SAFE_PROTOCOL_REGEX`

changedetectionio/__init__.py, price-finder
=> Re #1377 - Use year/date in the backup snapshot zip filename

changedetectionio/update_worker.py
=> Be sure to really not do anything in the case that the checksums were the same

changedetectionio/tests/test_filter_exist_changes.py, changedetectionio/update_worker.py
=> False change notifications - Don't reset watch checksum when a fetch error happens, adjust test to not test for fluctuating filter Re #962 

changedetectionio/__init__.py, changedetectionio/diff.py, changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/processors/text_json_diff.py, changedetectionio/run_basic_tests.sh, changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/edit.html, changedetectionio/tests/test_add_replace_remove_filter.py, changedetectionio/tests/test_block_while_text_present.py, changedetectionio/tests/test_unique_lines.py, changedetectionio/tests/unit/test_notification_diff.py, changedetectionio/update_worker.py
=> Ability to set which text to process (added, removed, changed) according to the difference

changedetectionio/__init__.py, changedetectionio/notification.py, changedetectionio/static/js/notifications.js
=> Re #1503 - Send test notification should use system defaults for body and title if not set in watch

changedetectionio/__init__.py, changedetectionio/static/styles/scss/parts/_pagination.scss, changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/_pagination.jinja, changedetectionio/templates/watch-overview.html, requirements.txt
=> Adding pagination

changedetectionio/__init__.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/processors/text_json_diff.py, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/tests/conftest.py, changedetectionio/tests/test_request.py
Re #1448 
https://github.com/dgtlmoon/changedetection.io/wiki/Adding-headers-from-an-external-file
=> Basic headers fetch from file

changedetectionio/store.py, changedetectionio/tests/test_notification.py, changedetectionio/update_worker.py
=> Fix notification settings

MANIFEST.in, changedetectionio/__init__.py, changedetectionio/blueprint/check_proxies/__init__.py, changedetectionio/processors/__init__.py, changedetectionio/processors/text_json_diff.py, changedetectionio/static/js/recheck-proxy.js, changedetectionio/static/styles/scss/parts/_extra_proxies.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/_helpers.jinja, changedetectionio/templates/edit.html
=> Helper button to trigger a scan/access test of all proxies for a particular watch

requirements.txt
=> apprise 1.4.5

.github/workflows/containers.yml, .github/workflows/test-container-build.yml, requirements.txt
=> Re-enable ARMv6 builds (for Raspberry and other portable devices)

.github/workflows/containers.yml, .github/workflows/test-container-build.yml
=> linux armv8 build

requirements.txt
adds Pushy, PushDeer, PushMe, Matrix attachment support (screenshots), various fixes
=> Update Apprise 1.4.5 -> 1.5.0

changedetectionio/run_proxy_tests.sh, changedetectionio/store.py, changedetectionio/tests/proxy_list/test_noproxy.py
Closes #1763
Adds a "No Proxy" option to the proxy list when proxies are enabled
=> No proxy option

changedetectionio/tests/test_backup.py
=> utf-8 in URL path that was breaking backup

changedetectionio/html_tools.py, changedetectionio/processors/text_json_diff.py, changedetectionio/tests/test_automatic_follow_ldjson_price.py
=> 1833 - LD JSON Properly handle lists of product type

changedetectionio/__init__.py, changedetectionio/static/js/diff-render.js, changedetectionio/static/styles/diff.css, changedetectionio/static/styles/scss/diff.scss, changedetectionio/templates/diff.html, changedetectionio/tests/test_backend.py
Closes #1846
Plus minor UI cleanup
=> Selectable dates between any version and minor UI cleanup for differences page

changedetectionio/tests/test_xpath_selector.py
=> Re #1774 - adding test for self closing tag that could break xpath

changedetectionio/html_tools.py, changedetectionio/processors/text_json_diff.py, changedetectionio/tests/test_rss.py
=> Handle CDATA in RSS correctly, generally handle RSS better

changedetectionio/html_tools.py, changedetectionio/processors/text_json_diff.py, changedetectionio/tests/test_rss.py
=> RSS fetch - Adding <title> workaround so filters work nicer

changedetectionio/__init__.py, changedetectionio/blueprint/browser_steps/__init__.py, changedetectionio/blueprint/browser_steps/browser_steps.py, changedetectionio/model/Watch.py, changedetectionio/static/js/browser-steps.js, changedetectionio/static/styles/scss/parts/_browser-steps.scss, changedetectionio/static/styles/styles.css, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/update_worker.py
First part is to make it more obvious where the error was
Next is the link to see the screenshot at error time
=> UI - BrowserSteps - Show the screenshot of an error if it happened on a step, highlight which step had the error

changedetectionio/blueprint/browser_steps/browser_steps.py, changedetectionio/content_fetcher.py
=> Going to a page was doing some different logic to BrowserSteps - make them use the same methods

changedetectionio/forms.py, changedetectionio/tests/test_extract_regex.py
=> Filters - "Extract text" was not being error checked properly

changedetectionio/content_fetcher.py, changedetectionio/tests/visualselector/test_fetch_data.py
=> Browser Step enabled watches should also identify 404 situations

changedetectionio/content_fetcher.py, changedetectionio/tests/visualselector/test_fetch_data.py
=> Wrong text taken from browser steps

Dockerfile
=> Upgrade to bookworm - fix glibc mismatch

Dockerfile
=> Upgrade playwright browser library

requirements.txt
related to https://github.com/dgtlmoon/changedetection.io/pull/1961
=> flask-login needs updating to resolve pip issue

.github/workflows/test-only.yml, changedetectionio/__init__.py, changedetectionio/model/Watch.py, changedetectionio/templates/watch-overview.html, changedetectionio/tests/unit/test_watch_model.py
=> Automatically set the correct "from date" in diff link button to be the closest to your last-viewed date

changedetectionio/api/api_v1.py, changedetectionio/model/Watch.py, changedetectionio/tests/test_api.py
=> Re #1998 - Make sure the watch "is viewed" attribute is correctly represented in the API output

changedetectionio/api/api_v1.py, changedetectionio/flask_app.py, changedetectionio/store.py, changedetectionio/tests/test_api.py
API - Add bulk list of watches
=> API - Add bulk list of watches

requirements.txt
=> Upgrade to Apprise 1.7.1

changedetectionio/update_worker.py
=> Using correct tokens for browser step failure notification

changedetectionio/notification.py, changedetectionio/tests/test_notification_errors.py
=> Notifications - When any in a list of notifications fails, the others should still work

changedetectionio/tests/smtp/test_notification_smtp.py
=> Adding extra test for #2103

changedetectionio/tests/test_backup.py
taken from https://github.com/dgtlmoon/changedetection.io/pull/722
not needed to write the zip to disk
=> Backups - Tidy up test

changedetectionio/content_fetcher.py
=> Improve status_code logging

changedetectionio/processors/text_json_diff.py
=> Filtering - "include filters" deduplicate including duplicate filters from group setting

changedetectionio/content_fetchers/res/stock-not-in-stock.js, changedetectionio/content_fetchers/res/xpath_element_scraper.js
actually  caused the browser to hang!
=> Fetching - restock detecting and visual selector scraper - Fixes scraping of elements that are not visible

changedetectionio/templates/import.html
CSS/Xpath filters were not being added on excel import due to a small typo on the select option
=> fixed typo on select

requirements.txt
https://github.com/dgtlmoon/changedetection.io/issues/2241
=> Pin mqtt to compatible version, update apprise

changedetectionio/flask_app.py, changedetectionio/static/js/notifications.js, changedetectionio/store.py
=> Re #2263  "send test notification" from watch edit should respect global settings and tag/group settings

changedetectionio/blueprint/tags/__init__.py, changedetectionio/blueprint/tags/templates/groups-overview.html
=> Tweaks to tag/groups page

changedetectionio/flask_app.py, changedetectionio/model/Watch.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_group.py
=> UI - Re #2307 - Adding UI notice if watch has group options set

changedetectionio/html_tools.py, changedetectionio/tests/test_xpath_selector.py, requirements.txt
=> module 'lxml.etree' has no attribute '_ElementStringResult' - reimplement _ElementStringResult

changedetectionio/notification.py, requirements.txt
Closes https://github.com/dgtlmoon/changedetection.io/issues/2324
=> Bump apprise to 1.8.0

changedetectionio/notification.py
=> Re #2299 Fixing truncated notifications

changedetectionio/flask_app.py
=> RSS - Muted watches should not show in RSS feed

changedetectionio/flask_app.py, changedetectionio/forms.py, changedetectionio/model/App.py, changedetectionio/store.py, changedetectionio/templates/settings.html
=> Setting to hide muted watches in RSS feed

changedetectionio/blueprint/browser_steps/browser_steps.py, changedetectionio/content_fetchers/base.py, changedetectionio/content_fetchers/res/__init__.py
=> Prefer pythons built in "importlib" over pkg_resources+setuptools

Dockerfile, requirements.txt
needs https://piwheels.org/project/cryptography/ python 3.11 only
=> Maybe this solves cryptography <-> rustc

changedetectionio/blueprint/tags/templates/edit-tag.html, changedetectionio/html_tools.py, changedetectionio/processors/text_json_diff.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_jsonpath_jq_selector.py
Builds on top of https://github.com/dgtlmoon/changedetection.io/pull/1744
Fixes: #1472
=> Implement jqraw

changedetectionio/api/api_v1.py, changedetectionio/blueprint/browser_steps/__init__.py, changedetectionio/model/Watch.py, changedetectionio/processors/__init__.py, changedetectionio/processors/restock_diff.py, changedetectionio/processors/text_json_diff.py, changedetectionio/store.py, changedetectionio/tests/test_api.py, changedetectionio/tests/test_history_consistency.py, changedetectionio/update_worker.py
=> saving snapshot html

changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/tests/test_backend.py, changedetectionio/update_worker.py
=> 2458 Snapshot count history not updated in watch after [clear history]

changedetectionio/flask_app.py, changedetectionio/notification.py, changedetectionio/tests/test_notification.py
=> Closes #2510

changedetectionio/content_fetchers/requests.py, changedetectionio/notification.py
Closes #1315
Closes #2309
Closes #6304
Closes #1995
=> Encode requests and notifications as UTF-8 if it has no encoding/basic string

changedetectionio/content_fetchers/base.py
=> Add encoding for scraper script reader

requirements.txt
=> Re #1708 unpin jsonschema

changedetectionio/processors/restock_diff/processor.py
Otherwise it will assume "in stock" because nothing suggesting the opposite was found
=> Only try to process restock information (like scraping for keywords) if the page was actually rendered correctly.

changedetectionio/flask_app.py, changedetectionio/forms.py, changedetectionio/processors/__init__.py, changedetectionio/processors/restock_diff/processor.py, changedetectionio/processors/text_json_diff/processor.py, changedetectionio/static/js/watch-settings.js, changedetectionio/static/styles/scss/parts/_preview_text_filter.scss, changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/base.html, changedetectionio/templates/edit.html, changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/tests/util.py, changedetectionio/update_worker.py
What it says :)
Makes life SO much easier
Extra filters that could help
- Clean whitespace before and after text
- Remove duplicates
=> UI - Live preview of text filters

changedetectionio/blueprint/tags/templates/edit-tag.html, changedetectionio/forms.py, changedetectionio/html_tools.py, changedetectionio/model/Watch.py, changedetectionio/processors/restock_diff/processor.py, changedetectionio/processors/text_json_diff/__init__.py, changedetectionio/processors/text_json_diff/processor.py, changedetectionio/static/js/watch-settings.js, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html, changedetectionio/tests/test_extract_regex.py, changedetectionio/tests/test_ignore_regex_text.py, changedetectionio/tests/test_ignore_text.py, changedetectionio/tests/unit/test_watch_model.py, changedetectionio/update_worker.py
(its utf-16 by default python string)
=> Misc fixes - juggling utf-8 not needed, improvements to whitespace filtering

changedetectionio/processors/restock_diff/processor.py, changedetectionio/tests/itemprop_test_examples/README.md, changedetectionio/tests/itemprop_test_examples/a.txt, changedetectionio/tests/proxy_socks5/test_socks5_proxy.py, changedetectionio/tests/test_restock_itemprop.py
=> Restock multiprice improvements

changedetectionio/processors/text_json_diff/processor.py, changedetectionio/tests/test_block_while_text_present.py
=> "Block change detection when text exists" should not trigger a change when the original text returns

changedetectionio/flask_app.py, changedetectionio/static/js/notifications.js, changedetectionio/tests/test_notification.py, changedetectionio/tests/test_restock_itemprop.py
=> "Send test notification" in "Restock" mode was not working correclty when restock tokens "{{restock.price}}" were in the notification body

.gitignore, changedetectionio/forms.py, changedetectionio/processors/__init__.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_request.py
Closes #2502
👋 This is an attempt to add jinja2 handling to request body (and headers). So far I've only got body here and want to confirm the implementation looks reasonable. Headers appears a bit more complicated, but should be doable.
I could also use some advice on what kind of tests to add. For jinja in the URL, I don't see anything in the requests tests. There is some testing in the jinja tests. Any opinion on where I should add a test?
=> #2502 - Add jinja2 template handling to request body

changedetectionio/flask_app.py
=> Re #2747 - Do not recheck 'paused' watches on edit/save

changedetectionio/html_tools.py, changedetectionio/tests/test_element_removal.py
=> Filters - Process all CSS and XPath 'subtract' selectors in a single pass to prevent index shifting and reference loss during DOM manipulation.

changedetectionio/blueprint/backups/__init__.py, changedetectionio/blueprint/backups/templates/overview.html, changedetectionio/flask_app.py, changedetectionio/templates/base.html, changedetectionio/tests/test_backup.py
Backups now launch in a background thread
=> Slightly better backup handling UI

changedetectionio/processors/restock_diff/processor.py
=> Price tracker - fix for sites that supply an empty additional price

changedetectionio/flask_app.py, docker-compose.yml
=> Disable version check option - #2773

.dockerignore, .gitignore
Try to unify the git and docker ignore files a little bit. This also ignores more byte-compiled files and some caches of tools that can help with finding errors (mypy, ruff).
These are just things I ran into while working on the code base. This doesn't change the final outputs but speeds up development a little bit.
=> Update .gitignore and .dockerignore

changedetectionio/forms.py, changedetectionio/notification.py
=> Re #2769 - Support for commented out notification URLs

changedetectionio/flask_app.py, changedetectionio/templates/edit.html, changedetectionio/templates/watch-overview.html
=> Re #2785 Make 'tag' sticky - redirect to current tag on edit or add watch

changedetectionio/api/api_v1.py, changedetectionio/tests/test_api.py, changedetectionio/tests/test_backend.py, changedetectionio/tests/test_nonrenderable_pages.py, changedetectionio/tests/util.py, changedetectionio/update_worker.py
=> Follow last_checked time improvements

changedetectionio/apprise_plugin/__init__.py, changedetectionio/tests/test_notification.py, changedetectionio/tests/util.py
=> Re #2896 204 and other 20x responses are OK

changedetectionio/templates/watch-overview.html
=> Fix mute/unmute alt/title label

changedetectionio/api/api_schema.py
=> Adding `browser_steps` JSON Schema rule for API updates

changedetectionio/model/Watch.py
Re #3041 Ensure atomic/safe history data disk writes
Closes #3041
=> Re #3041 Ensure atomic/safe history data disk writes

changedetectionio/blueprint/ui/__init__.py, changedetectionio/store.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_clone.py, changedetectionio/tests/test_group.py
=> Re #2782 - Should be "Clone & Edit" without watch history

changedetectionio/blueprint/ui/edit.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_backend.py, requirements.txt
Related to https://github.com/dgtlmoon/changedetection.io/issues/3108
=> Add levenshtein distance info

changedetection.py
=> Re #3115 fix multiprocessing start

changedetectionio/processors/__init__.py, changedetectionio/processors/restock_diff/processor.py, changedetectionio/processors/text_json_diff/__init__.py, changedetectionio/tests/custom_browser_url/test_custom_browser_url.py, changedetectionio/tests/proxy_socks5/test_socks5_proxy.py, changedetectionio/tests/proxy_socks5/test_socks5_proxy_sources.py, changedetectionio/tests/test_live_preview.py
replace some unnecessary f-strings by normal strings
=> remove unused f-strings

changedetectionio/blueprint/browser_steps/browser_steps.py
=> Handle execution context changes better in browsersteps

.github/workflows/test-stack-reusable-workflow.yml, changedetectionio/__init__.py, docker-compose.yml
=> Re #3247 Adding check and SSL setup

.github/workflows/test-stack-reusable-workflow.yml, changedetectionio/__init__.py, docker-compose.yml
=> IPv6 tidy-up

changedetectionio/model/__init__.py, changedetectionio/tests/test_api.py, changedetectionio/tests/test_conditions.py, changedetectionio/tests/unit/test_conditions.py
=> Fix set conditions by API 

changedetectionio/processors/text_json_diff/processor.py
=> Re #3406 fix list update

changedetectionio/blueprint/watchlist/templates/watch-overview.html, changedetectionio/model/Watch.py, changedetectionio/tests/test_ui.py
=> UI - Fixing HTML <title> versus custom title settings display in overview
