README.md, requirements.txt
Proxy can be passed [via environment variables](https://docs.python-requests.org/en/master/user/advanced/#proxies).
Related to #49
=> Add socks proxy support

backend/fetch_site_status.py
In this way diffs become easier to read and changes only in surrounding
whitespace but not in the textual content do not trigger false positives.
=> Strip surrounding whitespace from elements

backend/fetch_site_status.py, backend/forms.py, backend/templates/edit.html, backend/tests/test_jsonpath_selector.py, changedetection.py, requirements.txt
Re #117 jsonpath JSON change detection filter
For example
https://api.coindesk.com/v1/bpi/currentprice.json
This will re-parse the JSON and apply indent to the conversion
Todo:
- See how it fits in with the `javascript-browser` branch 
- rename vars? 
- Test how it works with errors (bad jsonpath rule, bad json document etc)
=> Re #117 Jsonpath based JSON change detection filter

backend/static/styles/styles.css, backend/static/styles/styles.scss, backend/templates/settings.html
The notification_title input is fixed with size=80, cause the page overflown in mobile view.
Use CSS to fit it instead
=> fix: setting overflow in mobile view

backend/__init__.py, backend/fetch_site_status.py, backend/forms.py, backend/store.py, backend/templates/edit.html, backend/tests/conftest.py, backend/tests/test_trigger.py, backend/tests/test_trigger_regex.py, backend/tests/test_trigger_regex_with_filter.py, backend/update_worker.py
=> Trigger text/wait

changedetectionio/__init__.py, changedetectionio/forms.py, changedetectionio/notification.py, changedetectionio/store.py, changedetectionio/templates/_common_fields.jinja, changedetectionio/tests/test_notification.py, changedetectionio/update_worker.py
This change enables defining the notification body as HTML or Markdown. This can be very
useful to have more user-friendly notifications such as:
* applying a heading style to the `{watch_title}` to make it stand out
* creating clickable links using the `{watch_url}`, `{preview_url}` and `{diff_url}`.
Changes
=======
* Add a `notification_format` to the notification settings, defaults to plain text.
* Use the `body_format` parameter of Apprise's `notify` method.
=> Configurable notification formats for apprise notifications ( Text / Markdown / HTML )

changedetectionio/content_fetcher.py
Thanks for your changes in https://github.com/dgtlmoon/changedetection.io/pull/326 to solve https://github.com/dgtlmoon/changedetection.io/issues/267. 
I'm getting the following error from the webdriver which this PR should solve it:
```
org.openqa.selenium.InvalidArgumentException: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
```
=> Add socksVersion mapping

changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/tests/test_jsonpath_selector.py, changedetectionio/tests/util.py
This avoids possible html code included in json to be stripped away by default.
Couldn't find a way to extract response headers from selenium.
Looks like it isn't possible...
=> Be sure that documents returned with a application/json header are not parsed with inscriptis

docker-compose.yml
Seleniarm has a working arm64 container for browser-chrome - tested on Oracle Cloud ARM server, not tested on rPi, as I don't have one available to test.
Added notes to the comments for the alternative container, and removed the note regarding rPi.
=> Working arm64 chrome-browser container

changedetectionio/__init__.py, changedetectionio/templates/import.html, changedetectionio/tests/test_import.py
With this small change, tags can be added inside the import by adding them after whitespace, ie:
```https://google.com search other``` 
will add google with two tags, `search` and `other`.
We are looking at using changedetection to track a larger number of websites, the URLs for which are added automatically and should be categorized. Hence I thought this was a useful change.
I had disabled black, but isort was still running, so the imports in `__init__.py` have been sorted as well. I thought it's fine to leave, as better organized imports don't hurt. If you'd rather not do this, I'm happy to revert those changes.
Also, PR onto `master` because `dev` seems to have been abandoned a short while ago?
=> Add option for tags on import

changedetectionio/fetch_site_status.py
plaintext mime type fix - Don't attempt to extract HTML content from …plaintext, this will remove lines and break changedetection
=> text/plain mime type fix - Don't lose line-feeds by parsing it as HTML ( text/plain documents were appearing as all on one line )

changedetectionio/html_tools.py
Unfortunately lxml only supports XPath 1.0. That is very limitted compared to XPath 2.0. But at least lxml allows usage of EXSLT functions, if you define the namespace: https://lxml.de/xpathxslt.html#regular-expressions-in-xpath
This PR adds a 're' namespace in order to enable re:test, re:math and re:replace.
=> Add re: namespace for regEx support in xpath

changedetectionio/.gitignore, changedetectionio/content_fetcher.py, changedetectionio/tests/test_encoding.py
If the response did not tell us what encoding format to expect, Then use chardet to override what `requests` thinks, but only for 'utf-8' for now
For example - some sites don't tell us it's utf-8, but return utf-8 content
This seems to not occur when using webdriver/selenium, it seems to detect the text encoding more reliably.
=> Auto-byte encoding for utf-8 when its not mentioned in the content-type header reply

changedetectionio/__init__.py, changedetectionio/content_fetcher.py, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_errorhandling.py, changedetectionio/tests/test_ignorestatuscode.py, changedetectionio/tests/util.py
There's a site i've been trying to watch that is `403`'ing (by their design) - this PR allows `changedetection.io` to ignore bad statuses when set as a site-specific setting.
sidenote: today i learned that `request`'s `bool(response)` is based on status code
=> Allow changedetector to ignore status codes as a per-site setting

changedetectionio/templates/edit.html
This PR fixes a typo in Filters & Triggers settings.
=> Fix typo in Trigger text instructions

changedetectionio/templates/login.html
to allow to start typing the password immediately, without a need for a mouse click.
Since typing the password is the only thing that can be done on the Login page, I think it would make sense to automatically focus the password input field.
=> Add autofocus attribute to password login field

changedetectionio/forms.py
This PR removes the tag length validation, such that watch groups may be longer than 35 characters long.
See #631.
=> Remove tag length validation

changedetectionio/static/js/visual-selector.js
=> Fixed: Calculate offsetX and offsetY for Visual Selector in Firefox

changedetectionio/__init__.py, changedetectionio/api/api_v1.py, changedetectionio/fetch_site_status.py, changedetectionio/model/App.py, changedetectionio/model/Watch.py, changedetectionio/store.py, changedetectionio/templates/watch-overview.html, changedetectionio/tests/test_api.py, changedetectionio/tests/test_element_removal.py, changedetectionio/tests/test_history_consistency.py, changedetectionio/tests/test_trigger.py, changedetectionio/tests/test_trigger_regex.py, changedetectionio/tests/test_trigger_regex_with_filter.py, changedetectionio/tests/util.py, changedetectionio/update_worker.py
- Better than SQLite for people using NFS as their storage
- Should stop the horrible memory leak when you have a very large amount of 'history'
todo
=> Move history data to a textfile

.github/workflows/containers.yml, README.md
- :latest should be :latest stable release according to a new release, and also the :0.xx.xx tag for the release
- :dev can be what ever is going on in `master`
Closes #695
=> Re #695 - stable :latest containers

changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/model/Watch.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_unique_lines.py
~~- [ ] limit to last x? (as a main system setting?)~~
Super handy for pages that just shuffle the content around! or when new products appear in a listing.
Don't trigger a change unless there is no content available when compared to all history saved
=> [feature] Filter option - Trigger only when NEW content (lines) are detected ( compared to earlier text snapshots )

changedetectionio/model/App.py
Following up on the ticket #369
=> Use environment variables to override settings (user-agent, timeout, workers)

changedetectionio/notification.py
Recreation of #748 after I accidentally broke the branch :)
This is an extension of the feature implemented in https://github.com/dgtlmoon/changedetection.io/pull/531. Apprise supports the link given directly by discord as a notification URL instead of having to modify the link to start with discord://. I have extended the rule that was implemented to include URLs that start with https://discord.com/api/webhooks/
=> Added discord webhook base url to truncation rules

changedetectionio/templates/edit.html, changedetectionio/templates/settings.html
TL;DR:  I'm an idiot.  This took *way* longer to figure out than it should have.
I was creating ignore regexes in individual watches and they were not working.  I was trying to watch some stuff on github, which has the annoying "rocket357 committed 2 minutes ago" type of stuff, so I formed the following regexes:
`/[0-9]* [a-zA-Z]*/ ago`
This obviously (now, after scratching my head for entirely too long heh) should be:
`/[0-9]* [a-zA-Z]* ago/`
The commits here just clarify that the regex needs to span the entire line as opposed to only having partial coverage of the ignore lines.
Probably overkill, but some of us need training wheels =)
=> Regex clarification

requirements.txt
Changelog: https://github.com/caronc/apprise/releases/tag/v1.0.0
Compare: https://github.com/caronc/apprise/compare/v0.9.9...v1.0.0
For me especially interesting due to https://github.com/caronc/apprise/pull/627 (enabling better notifications to Home Assistant)
=> Bump apprise to 1.0.0

changedetectionio/content_fetcher.py
atleast when watching google spreadsheets
88mb before, 191Mb after fetching (with this patch)
vs
88mb before, 224Mb after fetching (with this patch)
remaining low-hanging memory leak over at https://github.com/weblyzard/inscriptis/issues/65
=> Playwright memory improvement - Python GC workaround

README-pip.md, README.md, changedetectionio/fetch_site_status.py, changedetectionio/forms.py, changedetectionio/html_tools.py, changedetectionio/templates/edit.html, changedetectionio/tests/test_jsonpath_jq_selector.py, requirements.txt
JSONPath is great, but it can be fairly limited in what you can do with it. The ability so use jq would open a lot of possibilities as far as working with JSON data. This PR adds support for jq using the `jq:` prefix in the CSS/JSON/XPATH Filter text box on the Edit page
https://stedolan.github.io/jq/manual/
```
{
"items": [
{
"name": "Product A",
"priceInCents": 2500
},
{
"name": "Product B",
"priceInCents": 500
},
{
"name": "Product C",
"priceInCents": 2000
}
]
}
```
`jq:.items[] | . + { "priceInDollars": (.priceInCents / 100) } | select(.priceInDollars > 10)`
```
{
"name": "Product A",
"priceInCents": 2500,
"priceInDollars": 25
}
{
"name": "Product C",
"priceInCents": 2000,
"priceInDollars": 20
}
```
=> Adds support for jq

changedetectionio/changedetection.py, docker-compose.yml
Today changedetection will send a `Referer` header when a user clicks on one of the monitored websites. This leaks the hostname of where changedetection is running. This PR adds an option to hide the `Referer` header from monitored websites.
=> Hide the Referer header from monitored websites

changedetectionio/run_all_tests.sh
Hi,
I extended the test runner bash script to atomatically select the same playwright version as the one selected in the docker build for production.
=> use same version of playwright while running tests as in production builds

changedetectionio/__init__.py, changedetectionio/static/js/toggle-theme.js
Removes the route and instead sets a cookie on toggle using javascript.
`getDarkModeSetting` reads the cookie on the server side to ensure the correct mode is set on page refreshes.
=> Use cookies instead of store for darkmode

requirements.txt
Changelog: https://github.com/caronc/apprise/releases/tag/v1.2.1
Don't know why line 65 shows as changed, didn't do anything there (nor do I see an actual change)
=> Bump notification library

README.md
The releases link in the readme.MD file has a typo. Small PR to fix it. 
The rest of the issue template is not relevant here as it's not a product bug.
=> Fix releases link in readme.md

changedetectionio/content_fetcher.py
=> Playwright - Browser "Service Workers" should be enabled by default but unset via env var PLAYWRIGHT_SERVICE_WORKERS=block

requirements.txt
Updates `apprise` to 1.3.0
Release notes: https://github.com/caronc/apprise/releases/tag/v1.3.0
=> Update notification library 

changedetectionio/res/stock-not-in-stock.js
For example https://www.melopero.com/en/shop/raspberry-pi/boards/raspberrypizerowhconheaderpresaldato/ has "250 in stock" but also "out of stock" to the side which was confusing it
=> Restock monitor - identify the cases where the product is also definitely in stock

changedetectionio/static/js/tabs.js
Fixes back navigation when accessing tabbed pages.
The `.click()` added a new history entry and going back from there left the page in a broken state.
Changed `.click()` to `location.replace()` to replace the history state instead. Note `history.replaceState()` cannot be used here as it does not update the `:target` element which is what's currently used to display the active tab content or trigger a `hashchange` event used to update the active tab.
Fixes #1200
=> Fix back navigation

changedetectionio/content_fetcher.py, changedetectionio/res/xpath_element_scraper.js
- Does not require a new `node` process per URL watch
- Scales way better (rely on browserless instead of local infrastructure)
- Does not yet handle browsersteps but it will in the future
- Much faster spin up time
- Less memory required
This is because browserless's code will manage multiple `/function` calls in one node process, while playwright does not support any threaded ability
=> Use builtin node puppeteer handler browserless

changedetectionio/update_worker.py
Sometimes you might get an error like connection error
And then the app would fetch the document again, and decide not to do any processing because the checksum was the same
but then the old error was still showing.
=> When the document was the same, always assume there was no error, clear any previous errors

changedetectionio/content_fetcher.py, changedetectionio/processors/text_json_diff.py, changedetectionio/tests/test_jsonpath_jq_selector.py, changedetectionio/tests/util.py
For example - Playwright returns lowercase `content-type` while requests returns `Content-Type`
=> Sometimes the JSON and other functionality never caught the header, always compare against lowercased headers

Dockerfile
python:3.10-slim is now debian bookworm which libssl1.1 not provided.
So Dockerfile build is broken.
```
[21:49:16.600] #14 5.173 E: Unable to locate package libssl1.1
[21:49:16.603] #14 5.173 E: Couldn't find any package by glob 'libssl1.1'
[21:49:16.606] #14 5.173 E: Couldn't find any package by regex 'libssl1.1'
[21:49:16.725] #14 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     libssl1.1     libxslt1.1     poppler-utils     zlib1g     && apt-get clean && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
[21:49:16.811] #11 CANCELED
```
python:3.10-slim-bullseye will help.
```
$ docker run -it python:3.10-slim /bin/bash
root@435673e149be:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian …
```
=> Docker container updates - use specific debian version

changedetectionio/static/js/toggle-theme.js, changedetectionio/static/styles/styles.css, changedetectionio/templates/base.html
Fixes an issue where the initial state of the dark mode toggle is wrong when you are on dark mode.
The `dark` class was not being set properly on load. Removed the `dark` class manipulation so that `html[data-darkmode]` is the single source of dark mode state.
Before|After
-------|----
1. Enable dark mode.
2. Refresh the page.
=> Fix dark mode toggle

changedetectionio/html_tools.py, changedetectionio/tests/test_ignore_regex_text.py
=> Regex extra options in `ignore` and `trigger` were not processing correctly

README.md
[lxml](https://lxml.de/xpathxslt.html) uses xpath 1.0
> lxml supports XPath 1.0, XSLT 1.0 and the EXSLT extensions through libxml2 and libxslt in a standards compliant way.
Therefore newer xpath syntax cannot be used. (such as "matches").
See also [SO answer](https://stackoverflow.com/a/5929387/20307768)
=> README/docs: Clarifying xpath version changedetection.io uses

changedetectionio/diff.py, changedetectionio/notification.py, changedetectionio/templates/_common_fields.jinja, changedetectionio/tests/test_filter_exist_changes.py, changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/tests/test_group.py, changedetectionio/tests/test_notification.py, changedetectionio/tests/unit/test_notification_diff.py, changedetectionio/update_worker.py
Add `diff_patch` notification body token, allowing the diff to be displayed in unified format. Based on the discussion from #1538.
Notes:
- PR is being made against `master`, given that the `dev` branch is actually behind it.
- Usual patch header with file/URL and date is not being added, given that this information is currently not present anyway.
- ~Not sure if files like `changedetectionio/tests/test_notification.py` and `changedetectionio/tests/test_group.py` need to be changed, given that they have references for the other diff tokens (like `diff_full`). Tests haven't failed when running on GitHub Actions on my fork anyway.~ Edit: done.
Closes #1538
=> [Feature/1538] Add 'diff_patch' notification body token

changedetectionio/content_fetcher.py, changedetectionio/res/puppeteer_fetch.js, docker-compose.yml
Was setting the user agent to `Mozilla 5.0` in playwright if nothing was set/overriden, instead of letting playwright/puppeteer present the correct user agent, which may cause some sites to error or block
Closes #1809
=> Dont set user agent default if none is set

.github/workflows/codeql-analysis.yml, .github/workflows/containers.yml, .github/workflows/test-container-build.yml, .github/workflows/test-only.yml, .github/workflows/test-pip-build.yml
No breaking changes were found, so they can be directly upgraded.
Fixes Node 12 deprecation notices and "save-state" command deprecation notices
References:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Upgrade test workflows actions to latest versions

changedetectionio/__init__.py, changedetectionio/templates/watch-overview.html
So you can better manage watches with errors, really handy for long lists
=> Adding handy "limit to watches with errors" button

Dockerfile
Prebuilt armv6/armv7 wheels are available on piwheels for Python 3.7 (buster), Python 3.9 (bullseye) and soon Python 3.11 (bookworm).
In the future, when changedetection supports Python 3.11 we can unpin some requirements (in requirements.txt) and the build workflow won't fail due to missing Rust (it is required to compile some wheels like `rpds-py`).
(This is a repost of #1782)
=> Add piwheels support for ARMv6 and ARMv7 machines

changedetectionio/__init__.py, changedetectionio/tests/visualselector/test_fetch_data.py
It was very strange that sometimes this would find the file, and sometimes return 404
This also helps to run on different platforms (correct OS path join, instead of hard-coded forward slash)
=> Visual Selector - Improving elements fetcher reliability

Dockerfile
Reverts to building packages as a part of GitHub actions.
I realized piwheels provides incompatible packages to the `python:3.11-slim-bookworm` Docker container used by changedetection, and this broke Docker releases on ARM devices.
I apologize for any inconvenience caused.
=> Revert "Add piwheels support for ARMv6 and ARMv7 machines"

changedetectionio/processors/__init__.py
related to https://github.com/dgtlmoon/changedetection.io/issues/2019
=> Always use plain requests for PDF because otherwise we cant access the embed PDF in the browser

changedetectionio/notification.py, changedetectionio/templates/_common_fields.jinja, changedetectionio/tests/conftest.py, changedetectionio/tests/test_notification.py, changedetectionio/tests/util.py
Should work the same as https://github.com/caronc/apprise/wiki/Notify_Custom_JSON#header-manipulation
Todo
- check tokens are removed from URL (like in NotifyJSON)
- user/password/etc/etc handled (like in NotifyJSON)
=> Fixing support for headers in custom post://, posts:// etc notifications

.github/workflows/test-only.yml
https://github.com/dgtlmoon/changedetection.io/pull/2036#issuecomment-1852028368
> also weird thing, I dont see the output from sigshutdown_handler() when running pytest, so pytest might be shutting it down in a weird way
=> test: Improve signal test coverage

changedetectionio/forms.py
Hello,
This is a simple PR to add OPTIONS to the valid method list for configuring watches. It was needed because OPTIONS is a HTTP method that some endpoints accept in order to query API information. As such, it's useful for tracking changes.
=> Added OPTIONS HTTP method

changedetectionio/flask_app.py
Fixes #2103 and related discussion #2109
The notification format was not being set, and thus all html notifications were being sent as plaintext. Instead, the notification title was being set to the notification format if specified.
=> Bugfix: Notification title being set to notification format, notifiction format not being respected

requirements.txt
`tests/test_xpath_selector.py` was failing due to a change in elementpath in 4.2.0
=> elementpath~=4.1 fixes build error

changedetectionio/blueprint/tags/__init__.py, changedetectionio/blueprint/tags/templates/groups-overview.html, changedetectionio/flask_app.py, changedetectionio/templates/watch-overview.html
=> UI - Sort tag list and list of tags in groups setting

CONTRIBUTING.md
There’s no longer a `dev` branch and the project appears to be using `master` for this now.
=> Update contributing documentation for discontinuation of `dev` branch

changedetectionio/update_worker.py
This is also so that its easier to find these kinds of errors in the hosted solution
=> error text should contain the word Exception

changedetectionio/templates/base.html, changedetectionio/templates/watch-overview.html
Once `active_tag` was the UUID of the tag, but now it is a dict with the various properties of the tag. For building the different URLs we need to use the UUID.
This was broken since af747e6e3f66a0512317c0c6ea22e19bf622f192.
=> Use active_tag_uuid in URLs everywhere

changedetectionio/templates/base.html
`app_rss_token` is only set for the `watch-overview.html` template and we should not include a link without the token on other pages.
=> Only insert feed header if app_rss_token is set

changedetectionio/store.py
Better to fix the datasource than to add work-arounds in the code
Closes #1847
Closes #2456
=> 'tags'' field from old installs could have wrong data-type causing crash

changedetectionio/content_fetchers/res/xpath_element_scraper.js
When using Playwright if the XPath entry is something Chrome does not understand (i.e., XPath 2.0), it will throw an error when filtering visual elements using that XPath. This will cause the "results" variable to be empty. The next check is "results.length" which result in a null pointer dereference.
This results in an error seen on the web interface for the item:
Exception: TypeError: Cannot read properties of undefined (reading
'length') at eval (eval at evaluate (:226:30), <anonymous>:217:21)
at UtilityScript.evaluate (<anonymous>:233:19) at
UtilityScript.<anonymous> (<anonymous>:1:44)
This is a very confusing message because it does not have a reference to the original code file. An improvement might be to allow error messages to be passed back to the web UI when scraping the visual …
=> When scraping elements, check for null results

changedetectionio/content_fetchers/base.py, changedetectionio/content_fetchers/playwright.py, changedetectionio/content_fetchers/puppeteer.py, changedetectionio/content_fetchers/requests.py, changedetectionio/content_fetchers/webdriver_selenium.py, changedetectionio/processors/__init__.py, changedetectionio/templates/settings.html, changedetectionio/tests/test_nonrenderable_pages.py, changedetectionio/update_worker.py
=> Handle zero-byte responses with "`Empty pages are a change`" option, the same as when the HTML doesnt render any useful text

changedetectionio/blueprint/browser_steps/__init__.py
Hi there, I was testing some headers changes for a couple sites and was using the browser steps to quicky verify. Turns out, browser steps was not getting the headers I was setting but actual change detection attempts were. Either way, this seemed like a pretty straight forward addition to pass any pre-defined headers to the browser steps function.
I couldn't find tests for this section to modify but did test in my setup with both headers and no headers defined.
Thanks for developing such a great tool, looking forward to exploring more of it!
=> Pass headers to browsersteps

changedetectionio/processors/restock_diff/processor.py
This will check if there is any price defined twice and ensure their data types does not break the duplicated price check
Related: #2636
=> Fix duplicated prices with different data type on single page product #2636

changedetectionio/blueprint/browser_steps/browser_steps.py
This adds a browser step that allows to click element containing text if it exists, akin to already existing "click element if exists" action.
Note that it is effectively a copy of the "click element containing text" function. I can see that the regular "click element" function and "... if exists" variant of it are also a duplicated code, so I propose it as is, but it would be best to do an overall code refactoring in this class to reduce the redundancy.
=> browser_steps.py: add "click element containing text if exists"

changedetectionio/apprise_plugin/__init__.py, changedetectionio/blueprint/browser_steps/browser_steps.py, changedetectionio/blueprint/tags/templates/edit-tag.html, changedetectionio/flask_app.py, changedetectionio/forms.py, changedetectionio/html_tools.py, changedetectionio/notification.py, changedetectionio/processors/restock_diff/processor.py, changedetectionio/templates/_common_fields.html, changedetectionio/templates/edit.html, changedetectionio/templates/settings.html, changedetectionio/tests/test_element_removal.py, changedetectionio/tests/test_filter_failure_notification.py, changedetectionio/tests/test_restock_itemprop.py, changedetectionio/update_worker.py, requirements.txt
Similarly to how XPath selectors can be used to extract matching HTML elements, it would also be useful to remove HTML elements that match an XPath selector.
=> Add support for removing HTML elements using XPath selectors

changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css
This pull request addresses a number of mobile responsiveness issues:
1. Full width URL input field: Ensures that the URL input field takes up the full width of the container in a way that is consistent with other input fields
2. Align radio buttons: Makes radio buttons and labels start on the same line and wraps based on the length of the text content
3. Underline alignment: Aligns the underline at the bottom of the checkbox, pause button, and URL
4. Time input fields: Improve styling for the time input elements to give them a consistent appearance
5. Button size and spacing: Gives the action buttons consistent size and spacing
=> Fix for feedback on mobile styling

changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/watch-overview.html
This pull request addresses the wrapping issue on the sorting row for smaller screens to ensure that the table headers fit in one line. Minor HTML and CSS updates have been made.
=> Fix on sorting row wrapping issue

changedetectionio/forms.py, changedetectionio/static/styles/diff.css, changedetectionio/static/styles/scss/diff.scss, changedetectionio/static/styles/scss/parts/_extra_browsers.scss, changedetectionio/static/styles/scss/parts/_extra_proxies.scss, changedetectionio/static/styles/styles.css, changedetectionio/templates/diff.html, changedetectionio/templates/settings.html
This pull request addresses the mobile styling issues mentioned in #2701 :
1. Button color inconsistency: Fixed inconsistent font size and background color in action buttons.
2. Spacing issues: Corrects uneven spacing for extra proxies and extra browsers sections.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
3. Go button alignment: Fixed the misalignment issue for the Go button on the diff page.
While fixing the "Go" button alignment on the diff page, I noticed the diff page had a tendency to overflow, depending on the type of content in the diff results. For example, the ASCII art in changedetection.io diff page causes the page to overflow for small screens.  I narrowed it down to the styling in the diff …
=> Fix mobile styling inconsistencies and resolve diff page overflow issue

changedetectionio/apprise_plugin/__init__.py, changedetectionio/tests/test_notification.py
=> Re #2742 fixing URL encoding of headers so that '+' in URL is correctly parsed as ' ' (and other url-encodings)

requirements.txt
The paho-mqtt backwards compatibility problem was fixed with version 2.1.0, so we only need to avoid the 2.0.x series of releases. Upstream apprise is currently being tested with paho-mqtt 2.1.0 as part of my fix at https://github.com/caronc/apprise/pull/1238
This narrows the workaround for issue #2241
=> Narrow paho-mqtt requirement

changedetectionio/__init__.py
Solution for #1491 and #2257
Instead of using the `no-referrer` policy which blocks both same-origin and cross-origin referrers and breaks POST requests (login, saving settings, etc) inside the app, use the `same-origin` policy which allows the referrer inside the app while still blocking it outside the app.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#same-origin
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#same-origin_2
=> Fix HIDE_REFERER env option

changedetectionio/model/Watch.py, changedetectionio/templates/watch-overview.html, changedetectionio/tests/unit/test_watch_model.py
Fixes #2744 so that `get_from_version_based_on_last_viewed` returns snapshot before last viewed date instead of after.
=> Fix diff not starting from last viewed snapshot (#2744)

docker-compose.yml
Remove PUID and PGID because those configuration values are not used anywhere.
A user would expect this is working like in the linuxserver container images: https://docs.linuxserver.io/general/understanding-puid-and-pgid/
=> Remove unused PUID and PGID

changedetectionio/apprise_plugin/__init__.py, requirements.txt
Apprise [1.9.1](https://github.com/caronc/apprise/releases/tag/v1.9.1) includes some fixes for Matrix users particularly in that it allows one to use an access token for authentication instead of logging in for every request, thus avoiding login rate limits.
=> Update Apprise to 1.9.1

changedetectionio/tests/util.py, requirements.txt
This should cause a failure and be fixed when apprise is updated 
Re #2868
=> Make notifications use quotable URL for better testing

changedetectionio/tests/test_restock_itemprop.py
=> Re #2715 add test for new lower higher

changedetectionio/model/App.py, changedetectionio/tests/test_request.py
This fixes the `changedetectionio.store:get_all_headers_in_textfile_for_watch:559 - ERROR reading headers.txt at datastore/headers.txt too many values to unpack (expected 2)` error if the headers contain URLs.
=> Fix header parsing to split on the first colon only

.github/workflows/containers.yml
This PR will add additional tags to each release ([Rationale](https://medium.com/@mccode/using-semantic-versioning-for-docker-image-tags-dfde8be06699)). 
E.g. when releasing `10.59.6`, additional tags `10` and `10.59` are added. These allow users to pin their preferred major and/or minor version whilst still pulling in patch releases when they are released.
This is similar to what is offered by the alternative images by [chenio](https://hub.docker.com/r/chenio/changedetection.io). But I believe it's best to have this available at the original source project.
=> Add multiple semver tags to docker releases

docker-compose.yml
Fixing warning in up to date docker environments:
´´´
WARN[0000] /root/changedetection.io/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion  ´´
=> removing deprecated  docker version attribute

changedetectionio/tests/conftest.py, requirements.txt
I cannot run tests on windows because 'resource' library is not available on windows
> ModuleNotFoundError: No module named 'resource',
I replaced the 'resource' library with psutil: https://pypi.org/project/psutil/
> Cross-platform lib for process and system monitoring in Python.
=> Replace Linux only 'resource' library with cross-platform 'psutil' library

changedetectionio/blueprint/watchlist/__init__.py, changedetectionio/blueprint/watchlist/templates/watch-overview.html, changedetectionio/flask_app.py, changedetectionio/static/js/watch-overview.js, changedetectionio/update_worker.py
=> Set a graph % of ETA time completed of checking the watch

changedetectionio/model/Watch.py
Set to
x **Added lines**
x **Replaced/changed lines**
not **Removed lines**
somehow last-fetched.br was getting created with zero bytes
=> Small fix for when last fetched was zero bytes

changedetectionio/content_fetchers/webdriver_selenium.py
This is a one line change, which i tested on my win10 machine. It uses chromes own headless version, and shouldn't cause any issues.
=> Make chrome browser headless when checking the site with selenium

changedetectionio/blueprint/browser_steps/browser_steps.py, changedetectionio/content_fetchers/helpers.py, changedetectionio/content_fetchers/playwright.py, docker-compose.yml
This is a cleaner implementation than https://github.com/dgtlmoon/changedetection.io/pull/3089 for https://github.com/dgtlmoon/changedetection.io/discussions/3035 I think
Key changes:
- Don't create a list of all chunks and process at the end, process as we create the stitched image so we dont have a large amount of memory allocated to a list of chunks
- Use context managers for bytes and buffers
- Use constant viewport size (and thus chunk size) for stitching to eliminate need to adjust viewport size
- Lower clipped screenshot vertical limit from 32000px to 16000px
- Added an env var SCREENSHOT_MAX_HEIGHT to address https://github.com/dgtlmoon/changedetection.io/discussions/1760 and further provide a mitigation for limiting memory consumption (or increasing the limit if a user needs it) …
=> Memory fixes for large playwright screenshots

.github/workflows/test-only.yml, .gitignore, .pre-commit-config.yaml, .ruff.toml, requirements.txt
Hi. For a long time, I've had this repository in my bookmarks, but until recently I had never used it, even though I really liked the idea. Recently, I self-hosted it to track changes of some information on the web, and I found it very useful. In this regard, thanks to you and all the people behind the project!
I decided to contribute, as much as I can, to the project. However, I noticed that no tools are being used for code formatting and linting (black, flake8, ruff...). I believe it's important to have one that at least enforces code formatting, to avoid creating "noise" between PRs and to have a common style for everyone.
This PR introduces [Ruff](https://github.com/astral-sh/ruff), by Astral, among the dependencies, and its configuration (certainly opinionated by me, it's the one …
=> Development: introduce Ruff as linter/formatter

.github/workflows/test-stack-reusable-workflow.yml, changedetectionio/__init__.py
Previously logs were redirected inconsistently - only DEBUG and SUCCESS were sent to stdout while TRACE and INFO, both lower than SUCCESS, were sent to stderr. Now all levels at SUCCESS and lower are sent to stdout.
=> Send TRACE and INFO logs to stdout

changedetectionio/content_fetchers/playwright.py
Use `logger.debug` for playwright console logs instead of `print` so that the `LOGGER_LEVEL` setting can correctly hide these logs when set to a level above `DEBUG`.
=> Use logger.debug for playwright console logs

changedetectionio/static/styles/scss/styles.scss, changedetectionio/static/styles/styles.css
Having `max-width: 80%` is very frustrating.
I can see my browser window has enough space for a wider table, and yet the table cells are squished while leaving empty whitespace at the sides.
This is specially noticeable when using a non-wide monitor and resizing the browser to half of the monitor width. (In my case, 2240x1400 / 2 = 1120x1400.)
=> Don't restrict .box to 80% width

changedetectionio/store.py
Fixes #3260 #3259
(Found via good ol' `git bisect` for those who care. once you know the previous commit was the offender, the issue is pretty easy to spot)
=> Fix regression introduced by wrong indentation in previous commit

Dockerfile, docker-compose.yml
Related to https://github.com/dgtlmoon/changedetection.io/discussions/2514#discussioncomment-13900534
=> Ensure a default Locale is set for more reliable text decoding (en_US.UTF-8 by default)

changedetectionio/templates/base.html
Added robots meta with a noindex directive to stop search engines from indexing publicly exposed instances of Change Detection.
=> Block crawlers from indexing accidentally exposed instances
